# Explanation of the axis systhem transformation done in rotate_axis_system.py

In [8]:
import numpy as np

Lets take measurement examples: Each column i matrix X represent a measurement recording x, y, z components of the measurement vector. Hence, the matrix X below contains 4 measurements of 3-axis (x,y,z) vector.

In [9]:
x = [1, 1, 1, 1]
y = [2, 2, 2, 2]
z = [3, 3, 3, 3]
X = np.array([x, y, z])
X

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

We are then doing a axis transformation where we rotate x,y plane 90 degrees anticlockwise around the z-axis. The general transformation matrix for this rotation is 

$$
\begin{bmatrix}
cos \theta & -sin \theta & 0 \\
sin \theta & cos \theta & 0 \\
0 & 0 & 1
\end{bmatrix}
\\

\text{For } \theta = \frac{\pi}{2} \text{we get the transformation matrix A below.}
$$

The result should be a transformation where for each vector (x,y,z), the values are replaced with:
```
[x,y,z] = [-y,x,z]
```
This can be carried out with the matrix multiplication
```
[x,y,z] = A @ [x,y,z]
```
with
```
A = [
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1],
]
```
$$ \text{This is how the matrix multiplication works for } \\
A_z = AX \\
\text{ where } A_z \text{ is the result of the matrix multiplication} $$

The first row in A are the coefficients for calcuating x, the second y and the third row are for z component coming from each column of X (the measured values along the x,y,z axis).

In [10]:
print (f"X number of dimensions: {X.ndim}")
print(f"X shape: {X.shape}")
print(f"Data type: {X.dtype}")
A = np.array(
    [
        [0, -1, 0],
        [1, 0, 0],
        [0, 0, 1],
    ]
)

# Compute A_z the result of applying the rotation above to the input data X
A @ X

X number of dimensions: 2
X shape: (3, 4)
Data type: int64


array([[-2, -2, -2, -2],
       [ 1,  1,  1,  1],
       [ 3,  3,  3,  3]])

As A is an invertible matrix, The exist a Matrix that we can name A_inv such that 
```
 A_inv @ A = A @ A_inv = I
```
where `I` is the Identity matrix

This inverse matrix can be found using linear algebra with the function np.linalg.inv for instance.


In [11]:
A_inv = np.linalg.inv(A)

In [12]:
A @ A_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
A_inv @ A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

So if someone has applied a transformation A to the data X, one can revert the transformation by multiplying the transformed data with A_inv as
```
A_inv @ A @ X = I @ X = X
```


In [14]:
A_inv @ A @ X

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])